steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/master-thesis-prototype/streaming-server', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/master-thesis-prototype/streaming-server']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'streaming-server'
  - '--image'
  - 'gcr.io/master-thesis-prototype/streaming-server'
  - '--region'
  - 'europe-west3'
  - '--platform'
  - 'managed'
images:
- gcr.io/master-thesis-prototype/streaming-server
