volumes:
  configs-volume:

services:
  streaming-server:
    build: "./streaming-server"
    ports:
      - 1935:1935
      - 80:80
  config-server:
    build: "./config-server"
    volumes:
      - configs-volume:/var/www/configs
    environment:
      - PORT=80
      - CONFIGS_DIRECTORY=/var/www/configs
    ports:
      - 8080:80
  event-bridge:
    build: "./event-bridge"
    environment:
      - PORT=80
    ports:
      - 8081:80